# === Authorized scan scope — Sentinel SOC Phase 1 ===

# VLAN 7   — Management
10.201.0.0/16

# VLAN 21  — Wiping Network
10.21.0.0/16

# VLAN 61  — Printer Guys Network
192.168.61.0/24

# VLAN 301 — Floor Network
10.69.0.0/16

# VLAN 670 — Office
192.168.7.0/24

# VLAN 696 — Guest/Employees Wifi
192.168.8.0/24
